# nginx proxy address - http://172.17.0.1:59078

name: mattermost
x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

services:
  app:
    image: mattermost/mattermost-team-edition:latest
    container_name: mattermost-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      MM_ADMIN_USERNAME: ${APP_USER_NAME:-administrator}
      MM_ADMIN_EMAIL: ${APP_ADMIN_USER:-admin}@${BASE_DOMAIN_NAME:-${BASE_HOST_NAME}}
      MM_ADMIN_PASSWORD: ${APP_ADMIN_PASS:-changeme_admin_password}
      MM_SQLSETTINGS_DRIVERNAME: postgres
      MM_SERVICESETTINGS_SITEURL: https://${BASE_HOST_NAME:-$HOSTNAME}
      MM_SQLSETTINGS_DATASOURCE: postgres://${DB_USER_NAME:-dbadmin}:${DB_USER_PASS:-changeme_db_password}@mattermost-db:5432/${DB_CREATE_DATABASE_NAME:-mattermost}?sslmode=disable&connect_timeout=10
    ports:
      - '172.17.0.1:59078:8065'
    volumes:
      - './volumes/data/log/mattermost:/mattermost/logs'
      - './volumes/data/mattermost:/mattermost/data'
      - './volumes/data/mattermost/plugins:/mattermost/plugins'
      - './volumes/config/mattermost:/mattermost/config'
      - './volumes/config/mattermost/plugins:/mattermost/client/plugins'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mattermost

  db:
    image: postgres:alpine
    container_name: mattermost-db
    hostname: mattermost-db
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      POSTGRES_USER: ${DB_USER_NAME:-dbadmin}
      POSTGRES_DB: ${DB_CREATE_DATABASE_NAME:-mattermost}
      POSTGRES_PASSWORD: ${DB_USER_PASS:-changeme_db_password}
    volumes:
      - './volumes/data/db/postgres/mattermost:/var/lib/postgresql/data'
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', '${DB_USER_NAME:-dbadmin}', '-d', '${DB_CREATE_DATABASE_NAME:-mattermost}']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mattermost

networks:
  mattermost:
    name: mattermost
    external: false
